r"""Capstone Checkpoint 3.1 — Evaluation Infrastructure and Baseline Diagnosis (SOLUTION).
Jupytext-style cell markers (# %% / # %% [markdown]) — runnable as a
plain script AND openable as cells in VS Code / PyCharm / Jupytext.

This solution evaluates the Wikipedia Retrieval Engine capstone system with RAGAS
(an LLM-judge DiscreteMetric, exactly as in Lab 3.1), using the Checkpoint 2.1 HYBRID
retriever (BM25 + vector) over the Wikipedia corpus. It runs a SIDE-BY-SIDE comparison:

    * ORIGINALS   -> test_variables/test_main_questions.json
    * PARAPHRASES -> paraphrase variants derived from those originals
                     (test_variables/testinputs_variants.json, else the
                      testinputs_variant_questions.json paraphrase rows)

and reports each set's RAGAS pass rate plus the delta, which measures how brittle the
retriever is to rephrasing (the Lab 3.2 probe).
"""

# %% [markdown]
# # Capstone Checkpoint 3.1 — RAGAS Evaluation: Originals vs Paraphrases
# **MO-LLM Module 3 / Required Capstone Checkpoint**
#
# Uses RAGAS `DiscreteMetric` + `experiment()` (as in Lab 3.1) with the Checkpoint 2.1
# hybrid retriever. Evaluates two datasets separately and compares pass rates.

# %% [markdown]
# ## Setup
# 1. Python 3.11 or 3.12.
# 2. pip install -r requirements.txt (ragas, langchain-openai, langchain-chroma, rank-bm25, beautifulsoup4, python-dotenv, openai).
# 3. Use the OpenRouter API key provided for this program.
# 4. Create a `.env` file with:  OPENROUTER_API_KEY=sk-or-v1-...

# %%
from __future__ import annotations

import warnings
warnings.filterwarnings("ignore")

import os
import re
import json
import asyncio
from abc import ABC, abstractmethod
from datetime import datetime
from pathlib import Path

from bs4 import BeautifulSoup
from dotenv import load_dotenv
from langchain_chroma import Chroma
from langchain_core.documents import Document
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from openai import OpenAI
from rank_bm25 import BM25Okapi

from ragas import Dataset, experiment
from ragas.llms import llm_factory
from ragas.metrics import DiscreteMetric

# %%
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
LLM_MODEL = "openai/gpt-5.4-mini"          # answer model; covered by course credits
EMBEDDING_MODEL = "openai/text-embedding-3-small"
JUDGE_MODEL = "openai/gpt-5.4-mini"        # RAGAS judge model
TEMPERATURE = 0.2
TOP_K = 3
CANDIDATE_POOL = 10
WEIGHT_BM25 = 0.5
WEIGHT_VECTOR = 0.5

SCENARIO = "wikipedia"

# ── paths ────────────────────────────────────────────────────────────────
CHECKPOINT_DIR = Path(__file__).resolve().parent
FINAL_CAPSTONE_DIR = CHECKPOINT_DIR.parent
CHROMA_DIR = str(FINAL_CAPSTONE_DIR / "Capstone_Database" / "Capstone_Chroma_DB")
WIKI_DIR = str(FINAL_CAPSTONE_DIR / "Capstone_Database" / "Wikipedia")

ORIGINALS_PATH = CHECKPOINT_DIR / "test_variables" / "test_main_questions.json"
# Single combined variants file (100 originals + their LLM paraphrases), generated by
# test_variables/generate_variants.py. Paraphrases are the rows in this file that are
# NOT one of the originals in test_main_questions.json.
VARIANTS_PATH = CHECKPOINT_DIR / "test_variables" / "testinputs_variant_questions.json"

RAGAS_ROOT = str(CHECKPOINT_DIR / "ragas_experiments_3_1")
LOG_PATH = CHECKPOINT_DIR / "checkpoint_3_1_evaluation.log"
TEST_RESULTS_LOG = CHECKPOINT_DIR / "detailed_test_results.log"

ANSWER_SYSTEM = (
    "You are a helpful assistant for a Wikipedia retrieval engine. Answer the question "
    "using ONLY the provided Wikipedia article excerpts, and quote from them where you "
    "can. If the documents do not contain the answer, say so rather than guessing."
)


# %%
def require_api_key() -> None:
    if not os.environ.get("OPENROUTER_API_KEY"):
        load_dotenv()
    if not os.environ.get("OPENROUTER_API_KEY"):
        raise SystemExit(
            "\n[setup] OPENROUTER_API_KEY is not set.\n"
            "  Create a file named '.env' with: OPENROUTER_API_KEY=sk-or-your-key-here\n"
        )


def get_embeddings() -> OpenAIEmbeddings:
    return OpenAIEmbeddings(
        model=EMBEDDING_MODEL,
        api_key=os.environ["OPENROUTER_API_KEY"],
        base_url=OPENROUTER_BASE_URL,
        check_embedding_ctx_length=False,
    )


def log(label: str, text: str) -> None:
    ts = datetime.now().isoformat(timespec="seconds")
    with LOG_PATH.open("a", encoding="utf-8") as fh:
        fh.write(f"[{ts}] {label}\n{text}\n{'-' * 72}\n")


# %% [markdown]
# ## Corpus loading (persisted Chroma preferred, else scan Wikipedia HTML)

# %%
def load_wikipedia_docs(wiki_dir: str = WIKI_DIR) -> list[dict]:
    if not os.path.isdir(wiki_dir):
        print(f"Warning: Wikipedia directory not found at {wiki_dir}")
        return []
    docs = []
    html_files = sorted(f for f in os.listdir(wiki_dir) if f.endswith(".html"))
    print(f"Loading {len(html_files)} Wikipedia articles from {wiki_dir}/ ...")
    for idx, filename in enumerate(html_files, 1):
        try:
            with open(os.path.join(wiki_dir, filename), "r", encoding="utf-8", errors="replace") as fh:
                soup = BeautifulSoup(fh.read(), "html.parser")
            for tag in soup(["script", "style"]):
                tag.decompose()
            text = " ".join(soup.get_text(separator=" ", strip=True).split())
            if text:
                docs.append({"id": filename.replace(".html", ""), "text": text})
        except Exception as exc:
            print(f"  Error reading {filename}: {exc}")
        if idx % 200 == 0 or idx == len(html_files):
            print(f"  Progress: {idx}/{len(html_files)} ({len(docs)} valid)")
    print(f"Loaded {len(docs)} articles.")
    return docs


def load_docs_from_chroma(chroma_dir: str = CHROMA_DIR) -> list[dict]:
    if not os.path.isdir(chroma_dir) or not os.listdir(chroma_dir):
        return []
    db = Chroma(persist_directory=chroma_dir, embedding_function=get_embeddings())
    try:
        results = db.get(include=["documents", "metadatas"])
    except Exception as exc:
        print(f"Warning: could not read persisted Chroma docs: {exc}")
        return []
    docs = []
    for doc_id, text, meta in zip(
        results.get("ids", []), results.get("documents", []), results.get("metadatas", [])
    ):
        if not text:
            continue
        docs.append({"id": str((meta or {}).get("id", doc_id)), "text": text})
    print(f"Loaded {len(docs)} documents from existing Chroma DB at {chroma_dir}/")
    return docs


# %% [markdown]
# ## Hybrid retriever (BM25 + Vector) — from Checkpoint 2.1

# %%
_STOPWORDS = {
    "a", "an", "the", "and", "but", "or", "nor", "so", "yet", "for",
    "in", "on", "at", "to", "of", "by", "with", "from", "into", "onto", "upon",
    "about", "above", "below", "between", "through", "during", "before", "after",
    "under", "over", "around", "along", "across", "is", "are", "was", "were",
    "be", "been", "being", "have", "has", "had", "do", "does", "did",
    "i", "we", "you", "he", "she", "it", "they", "me", "us", "him", "her", "them",
    "my", "our", "your", "his", "its", "their", "this", "that", "these", "those",
    "as", "if", "up", "out", "not", "no",
}


def tokenize(text: str) -> list[str]:
    return [t for t in re.findall(r"[a-z0-9]+", text.lower()) if t not in _STOPWORDS]


def build_or_load_db(docs: list[dict], chroma_dir: str = CHROMA_DIR) -> Chroma:
    if os.path.isdir(chroma_dir) and os.listdir(chroma_dir):
        print(f"Loading existing vector DB from {chroma_dir}/")
        return Chroma(persist_directory=chroma_dir, embedding_function=get_embeddings())
    print(f"Building vector DB (first run — embedding {len(docs)} documents)...")
    os.makedirs(chroma_dir, exist_ok=True)
    doc_objs = [Document(page_content=d["text"], metadata={"id": d["id"]}) for d in docs]
    db = Chroma(persist_directory=chroma_dir, embedding_function=get_embeddings())
    batch = 50
    for i in range(0, len(doc_objs), batch):
        chunk = doc_objs[i:i + batch]
        db.add_documents(chunk, ids=[d.metadata["id"] for d in chunk])
        print(f"  Embedded {min(i + batch, len(doc_objs))}/{len(doc_objs)}")
    print(f"Indexed {len(docs)} documents into {chroma_dir}/")
    return db


def _normalize(scores: list[float], invert: bool = False) -> list[float]:
    if not scores:
        return []
    lo, hi = min(scores), max(scores)
    if hi == lo:
        return [0.5] * len(scores)
    norm = [(s - lo) / (hi - lo) for s in scores]
    return [1.0 - n for n in norm] if invert else norm


class BaseRetriever(ABC):
    def __init__(self, llm_model: str = LLM_MODEL):
        self._llm = ChatOpenAI(
            model=llm_model,
            api_key=os.environ["OPENROUTER_API_KEY"],
            base_url=OPENROUTER_BASE_URL,
            temperature=TEMPERATURE,
        )

    @abstractmethod
    def retrievedContext(self, query: str) -> str:
        ...

    def query(self, question: str) -> str:
        context = self.retrievedContext(question)
        messages = [
            SystemMessage(content=ANSWER_SYSTEM),
            HumanMessage(content=f"Context (Wikipedia excerpts):\n{context}\n\nQuestion: {question}"),
        ]
        response = self._llm.invoke(messages)
        return response.content if hasattr(response, "content") else str(response)


class HybridRetriever(BaseRetriever):
    """Hybrid retriever fusing BM25 (keyword) and vector (semantic) search."""

    def __init__(self, docs: list[dict], **kwargs):
        super().__init__(**kwargs)
        self._doc_ids = [d["id"] for d in docs]
        self._doc_texts = [d["text"] for d in docs]
        self._bm25 = BM25Okapi([tokenize(t) for t in self._doc_texts])
        self._db = build_or_load_db(docs, CHROMA_DIR)
        print(f"Hybrid retriever ready over {len(docs)} documents.")

    def _bm25_topk(self, query: str, k: int):
        scores = self._bm25.get_scores(tokenize(query))
        top = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)[:k]
        return [(self._doc_ids[i], self._doc_texts[i], scores[i]) for i in top]

    def _vector_topk(self, query: str, k: int):
        results = self._db.similarity_search_with_score(query, k=k)
        return [(d.metadata.get("id", "unknown"), d.page_content, s) for d, s in results]

    def getTopK(self, query: str, k: int):
        bm = self._bm25_topk(query, CANDIDATE_POOL)
        vec = self._vector_topk(query, CANDIDATE_POOL)
        content_by_id: dict[str, str] = {}
        bm_norm: dict[str, float] = {}
        vec_norm: dict[str, float] = {}
        if bm:
            for (doc_id, content, _), val in zip(bm, _normalize([s for _, _, s in bm])):
                content_by_id[doc_id] = content
                bm_norm[doc_id] = val
        if vec:
            for (doc_id, content, _), val in zip(vec, _normalize([d for _, _, d in vec], invert=True)):
                content_by_id[doc_id] = content
                vec_norm[doc_id] = val
        fused = [
            (doc_id, content,
             WEIGHT_BM25 * bm_norm.get(doc_id, 0.0) + WEIGHT_VECTOR * vec_norm.get(doc_id, 0.0))
            for doc_id, content in content_by_id.items()
        ]
        fused.sort(key=lambda t: t[2], reverse=True)
        return fused[:k]

    def retrievedContext(self, query: str) -> str:
        results = self.getTopK(query, TOP_K)
        return "\n\n---\n\n".join(f"[{doc_id}]\n{content}" for doc_id, content, _ in results)


# %% [markdown]
# ## RAGAS evaluation harness (DiscreteMetric judge — same idea as Lab 3.1)

# %%
def make_judge():
    return llm_factory(
        JUDGE_MODEL,
        client=OpenAI(api_key=os.environ["OPENROUTER_API_KEY"], base_url=OPENROUTER_BASE_URL),
    )


judge = None  # built in main() after the API-key check

correctness_metric = DiscreteMetric(
    name="correctness",
    prompt=(
        "You are grading a retrieval-augmented answer against reference grading notes.\n"
        "Return 'pass' if the response is factually consistent with the grading notes and "
        "captures their main point(s) — even if it omits some minor details or is worded "
        "differently. Return 'fail' only if the response contradicts the notes, is "
        "unsupported by them, or misses the central point.\n"
        "Response: {response}\nGrading Notes: {grading_notes}"
    ),
    allowed_values=["pass", "fail"],
)


# %% [markdown]
# ## Datasets — originals vs paraphrases (Step 3)

# %%
def _load_json(path: Path) -> list[dict]:
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def load_split_datasets() -> tuple[Dataset, Dataset]:
    """Build two RAGAS datasets from a single combined variants file.

    Originals come from test_main_questions.json. Paraphrases are the paraphrase-only
    rows of testinputs_variant_questions.json -- i.e., every row whose question text is
    NOT one of the originals. This keeps the originals-vs-paraphrases comparison
    apples-to-apples, since the paraphrases are derived from the same originals.
    """
    if not ORIGINALS_PATH.exists():
        raise FileNotFoundError(f"Originals not found at {ORIGINALS_PATH}")
    if not VARIANTS_PATH.exists():
        raise FileNotFoundError(
            f"Variants file not found at {VARIANTS_PATH}. Generate it first with "
            f"generate_variants.py."
        )

    originals = _load_json(ORIGINALS_PATH)
    original_questions = {o["question"].strip() for o in originals}

    combined = _load_json(VARIANTS_PATH)
    # paraphrases = rows in the combined file that are NOT one of the originals
    paraphrases = [r for r in combined if r["question"].strip() not in original_questions]

    def _to_dataset(name: str, rows: list[dict]) -> Dataset:
        ds = Dataset(name=name, backend="local/csv", root_dir=RAGAS_ROOT)
        for r in rows:
            ds.append({"question": r["question"], "grading_notes": r["grading_notes"]})
        ds.save()
        return ds

    return (
        _to_dataset("wiki_eval_originals", originals),
        _to_dataset("wiki_eval_paraphrases", paraphrases),
    )


# %% [markdown]
# ## Experiment (Step 4)

# %%
# ── progress tracking (shared across the current experiment run) ──────────
_PROGRESS = {"done": 0, "total": 0, "label": ""}


def _reset_progress(label: str, total: int) -> None:
    _PROGRESS["done"] = 0
    _PROGRESS["total"] = total
    _PROGRESS["label"] = label


def _tick_progress(question: str, verdict: str) -> None:
    """Print a one-line progress update as each question finishes scoring."""
    _PROGRESS["done"] += 1
    n, total, label = _PROGRESS["done"], _PROGRESS["total"], _PROGRESS["label"]
    preview = (question[:60] + "...") if len(question) > 60 else question
    print(f"  [{label}] {n}/{total} tested  ({verdict.upper()})  {preview}")


def build_experiment(retriever: BaseRetriever, kind: str):
    @experiment()
    async def run_experiment(row):
        response = retriever.query(row["question"])
        score = correctness_metric.score(
            llm=judge,
            response=response,
            grading_notes=row["grading_notes"],
        )
        _tick_progress(row["question"], str(score.value))
        return {**row, "retriever": kind, "response": response, "score": score.value}

    return run_experiment


async def _evaluate(retriever: BaseRetriever, dataset: Dataset, label: str) -> dict:
    total = len(dataset)
    print(f"\nEvaluating {label}: {total} questions with the hybrid retriever...")
    _reset_progress(label, total)
    results = await build_experiment(retriever, "hybrid").arun(dataset)
    passes = sum(1 for r in results if r["score"] == "pass")
    total = len(results)
    failures = [r["question"] for r in results if r["score"] != "pass"]
    results.save()
    csv_path = Path(RAGAS_ROOT) / "experiments" / f"{results.name}.csv"
    print(f"  {label}: {passes}/{total} passed  ->  {csv_path.resolve()}")
    log(f"{label} RESULT", f"{passes}/{total} passed; csv={csv_path}")
    return {
        "label": label,
        "passes": passes,
        "total": total,
        "failures": failures,
        "csv_path": str(csv_path),
    }


def append_test_results(originals: dict, paraphrases: dict, delta: float, verdict: str) -> None:
    """Append a structured, medium-detail entry to test_results.log for each run."""
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M:%S")

    def _rate(d: dict) -> str:
        return f"{d['passes']}/{d['total']} ({(d['passes'] / d['total'] * 100) if d['total'] else 0:.0f}%)"

    def _fail_block(d: dict) -> str:
        if not d["failures"]:
            return "  Failures    : none\n"
        lines = ["  Failures    : {} question(s) FAILED".format(len(d["failures"]))]
        for i, q in enumerate(d["failures"], 1):
            preview = q if len(q) <= 110 else q[:107] + "..."
            lines.append(f"    {i}. {preview}")
        return "\n".join(lines) + "\n"

    entry = []
    entry.append("=" * 80)
    entry.append(f"TEST SESSION  |  {date_str} {time_str}")
    entry.append("=" * 80)
    entry.append("Test type   : Baseline RAGAS correctness evaluation (hybrid retriever)")
    entry.append(f"Date        : {date_str}")
    entry.append(f"Time        : {time_str}")
    entry.append("Config      : Hybrid BM25+Vector (0.5/0.5), Top-K=4, "
                 f"answer={LLM_MODEL}, judge={JUDGE_MODEL}, metric=RAGAS DiscreteMetric")
    entry.append("")
    entry.append("-" * 80)
    entry.append("ORIGINAL QUESTIONS")
    entry.append("-" * 80)
    entry.append(f"  Dataset     : {ORIGINALS_PATH.name}")
    entry.append(f"  Result      : {_rate(originals)} PASSED")
    entry.append(f"  Output CSV  : {originals['csv_path']}")
    entry.append(_fail_block(originals).rstrip("\n"))
    entry.append("")
    entry.append("-" * 80)
    entry.append("PARAPHRASED QUESTIONS")
    entry.append("-" * 80)
    entry.append(f"  Dataset     : {VARIANTS_PATH.name} (paraphrase rows)")
    entry.append(f"  Result      : {_rate(paraphrases)} PASSED")
    entry.append(f"  Output CSV  : {paraphrases['csv_path']}")
    entry.append(_fail_block(paraphrases).rstrip("\n"))
    entry.append("")
    entry.append("-" * 80)
    entry.append("SIDE-BY-SIDE COMPARISON (rephrasing robustness)")
    entry.append("-" * 80)
    o_rate = (originals["passes"] / originals["total"]) if originals["total"] else 0.0
    p_rate = (paraphrases["passes"] / paraphrases["total"]) if paraphrases["total"] else 0.0
    entry.append(f"  ORIGINALS    : {originals['passes']}/{originals['total']}  =  {o_rate:.0%}")
    entry.append(f"  PARAPHRASES  : {paraphrases['passes']}/{paraphrases['total']}  =  {p_rate:.0%}")
    entry.append(f"  DELTA        : {delta:+.0%}")
    entry.append(f"  Verdict      : {verdict}")
    entry.append("=" * 80)
    entry.append("")

    with TEST_RESULTS_LOG.open("a", encoding="utf-8") as fh:
        fh.write("\n".join(entry) + "\n")
    print(f"Test results appended to: {TEST_RESULTS_LOG}")


# %% [markdown]
# ## Main — side-by-side comparison

# %%
async def main():
    require_api_key()
    global judge
    judge = make_judge()

    # Load corpus (persisted Chroma preferred)
    if os.path.isdir(CHROMA_DIR) and os.listdir(CHROMA_DIR):
        print(f"Chroma DB found at {CHROMA_DIR}/ — loading persisted documents.")
        docs = load_docs_from_chroma(CHROMA_DIR) or load_wikipedia_docs()
    else:
        print(f"Chroma DB not found — scanning Wikipedia HTML files.")
        docs = load_wikipedia_docs()

    retriever = HybridRetriever(docs)
    originals_ds, paraphrases_ds = load_split_datasets()

    originals = await _evaluate(retriever, originals_ds, "ORIGINALS")
    paraphrases = await _evaluate(retriever, paraphrases_ds, "PARAPHRASES")

    orig_rate = (originals["passes"] / originals["total"]) if originals["total"] else 0.0
    para_rate = (paraphrases["passes"] / paraphrases["total"]) if paraphrases["total"] else 0.0
    delta = para_rate - orig_rate

    if delta < -0.05:
        verdict = "BRITTLE to rephrasing: paraphrases score lower than originals."
    elif delta > 0.05:
        verdict = "Paraphrases scored higher -- check for lucky wording or judge leniency."
    else:
        verdict = "ROBUST to rephrasing: pass rates are comparable."

    print("\n" + "=" * 72)
    print("SIDE-BY-SIDE COMPARISON  (RAGAS correctness, hybrid retriever)")
    print("-" * 72)
    print(f"  ORIGINALS    : {originals['passes']}/{originals['total']}  =  {orig_rate:.0%}")
    print(f"  PARAPHRASES  : {paraphrases['passes']}/{paraphrases['total']}  =  {para_rate:.0%}")
    print(f"  DELTA (para - orig) : {delta:+.0%}")
    print("-" * 72)
    print(f"  {verdict}")
    print("=" * 72)
    log("COMPARISON",
        f"originals={originals['passes']}/{originals['total']} ({orig_rate:.0%}); "
        f"paraphrases={paraphrases['passes']}/{paraphrases['total']} ({para_rate:.0%}); delta={delta:+.0%}")

    # Append a structured, medium-detail entry to test_results.log
    append_test_results(originals, paraphrases, delta, verdict)


if __name__ == "__main__":
    asyncio.run(main())
